version: '3.8'

services:
  geth-node:
    image: pavelsborisov/go-ethereum-fork:latest
    container_name: ethereum-node
    ports:
      - "8545:8545"
      - "30303:30303"
    # Not mounting any volumes for now as this is a sample devnet so no need to persist data
    command: >
      --dev
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api eth,net,web3
      --http.corsdomain "*"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api eth,net,web3
      --ws.origins "*"
