---
- name: Configure kubectl
  command: gcloud container clusters get-credentials geth-hardhat-cluster --region {{ region }} --project {{ project_id }}
  register: gcloud_output
  failed_when: gcloud_output.rc != 0

- name: Apply Kubernetes deployment and service
  command: kubectl apply -f {{ playbook_dir }}/k8s-manifests/deployment.yml
  register: gcloud_output
  failed_when: gcloud_output.rc != 0